server:
  port: 8082
  fullAddress: ${HOST:http://localhost}:${PORT:${server.port}}

spring:
  application:
    name: operador-service

  datasource:
      url: jdbc:mysql://monorail.proxy.rlwy.net:27601/operador
      username: root
      password: KJCgKEczAzTmbVriQjoqukpDnGLWTtgg
      driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
      hibernate:
        ddl-auto: validate
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    preferIpAddress: false
    hostname: unirsoft-operador-production.up.railway.app


orderProduct:
  url: http://buscador-service/api/pelicula/%s